services:
  - type: web
    name: table-tennis-tournament
    env: node
    rootDir: my-project
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
